In [1]:
import numpy as np

In [2]:

A = np.array([
    [0,1,-1],
    [1,2,3],
    [2,1,0],
    [-1,2,-4]
])
B = np.array([
    [0,2],
    [1,1],
    [-1,-2]
])
print(A)
print(B)
print(A[1][1])
print(A[3][0])


[[ 0  1 -1]
 [ 1  2  3]
 [ 2  1  0]
 [-1  2 -4]]
[[ 0  2]
 [ 1  1]
 [-1  2]]
2
-1
