In [1]:
import numpy

## 기본 문법

In [2]:
arr1 = numpy.array([2,3,5,7,11,13,17,19,23,29,31])

In [3]:
arr1

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31])

In [4]:
type(arr1)

numpy.ndarray

In [5]:
arr1.shape

(11,)

In [6]:
arr2 = numpy.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [7]:
arr2


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
arr2.shape # 2차원 array

(3, 4)

In [9]:
type(arr2) # n dimentional array

numpy.ndarray

In [10]:
arr1.size

11

In [11]:
arr2.size

12

In [12]:
print(arr1)
print(arr2)

[ 2  3  5  7 11 13 17 19 23 29 31]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [13]:
arr3 = numpy.full(6,7)
print(arr3)

[7 7 7 7 7 7]


## 0으로 채우기 및 특정 값으로 채우기

In [14]:
arr4 = numpy.full(6,0)
print(arr4)
arr4 = numpy.zeros(6,dtype=int)
print(arr4)

[0 0 0 0 0 0]
[0 0 0 0 0 0]


In [15]:
arr5 = numpy.full(6,1)
print(arr5)
arr5 = numpy.ones(6,dtype=int)
print(arr5)

[1 1 1 1 1 1]
[1 1 1 1 1 1]


In [16]:
arr6 = numpy.random.random(6)
arr7 = numpy.random.random(6)
print(arr6)
print(arr7)

[0.1515153  0.9543317  0.66437604 0.12518036 0.45389392 0.2974025 ]
[0.00804534 0.93967314 0.50728091 0.91315678 0.07642518 0.25475749]


In [17]:
arr8 = numpy.arange(6)
print(arr8)
arr8 = numpy.arange(2,7)
print(arr8)
arr8 = numpy.arange(1,10,2)
print(arr8)

[0 1 2 3 4 5]
[2 3 4 5 6]
[1 3 5 7 9]


## Slicing

In [18]:
import numpy as np
arr9 = np.array([1,2,3,4,5,6,7,8,9])

In [19]:
arr9[-1]

9

In [21]:
arr9

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
arr9[-2:]

array([8, 9])

In [24]:
arr9[1::2]

array([2, 4, 6, 8])

## 활용

In [30]:
print(arr9/2)
print(arr9**2)



[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[ 1  4  9 16 25 36 49 64 81]


In [37]:
arr9 = arr9 + arr9
arr9

array([ 64, 128, 192, 256, 320, 384, 448, 512, 576])

## Boolean 연산

In [39]:
arr10 = np.array([2,3,5,7,9,11,13,17,19])


In [40]:
arr10>4

array([False, False,  True,  True,  True,  True,  True,  True,  True])

In [41]:
arr10 %2 ==0

array([ True, False, False, False, False, False, False, False, False])

In [42]:
booleans = np.array([True,True,False,False,True])

In [43]:
np.where(booleans)

(array([0, 1, 4]),)

In [44]:
np.where(arr10>4)

(array([2, 3, 4, 5, 6, 7, 8]),)

In [45]:
filter = np.where(arr10>4)
filter

(array([2, 3, 4, 5, 6, 7, 8]),)

In [46]:
arr10[filter]

array([ 5,  7,  9, 11, 13, 17, 19])

## Numpy array VS List
- numpy : 한가지 자료형만 가능, 속도 빠름, 연산 많을 때 사용
- List : 여러가지 자료형 가능, 느림, 삽입 삭제 등 간단한 연산만 있을 때 사용

## 기본적인 통계 기능

In [48]:
array1 = np.array([14, 6, 13, 21, 23, 31, 9, 5])

print(array1.max()) # 최댓값
print(array1.min()) # 최솟값

31
5


In [49]:
array1 = np.array([14, 6, 13, 21, 23, 31, 9, 5])

print(array1.mean()) # 평균값

15.25


In [50]:
array1 = np.array([8, 12, 9, 15, 16])
array2 = np.array([14, 6, 13, 21, 23, 31, 9, 5])

print(np.median(array1)) # 중앙값
print(np.median(array2)) # 중앙값

12.0
13.5


In [51]:

array1 = np.array([14, 6, 13, 21, 23, 31, 9, 5])

print(array1.std()) # 표준 편차
print(array1.var()) # 분산

8.496322733983215
72.1875
