In [5]:
import numpy as np

## numpy 행렬 기본 문법

In [6]:
A = np.array([
    [1,-1,2],
    [3,2,2],
    [4,1,2],
    [7,5,6]
])
A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2],
       [ 7,  5,  6]])

In [7]:
B = np.array([
    [0,1],
    [-1,3],
    [5,2]
])
B

array([[ 0,  1],
       [-1,  3],
       [ 5,  2]])

In [8]:
C = np.random.rand(3,5) # 0~1 random value
C

array([[0.91571098, 0.56784833, 0.12693403, 0.38227799, 0.84668453],
       [0.79390385, 0.26569753, 0.08478224, 0.05510773, 0.82023569],
       [0.67502213, 0.56203404, 0.07290756, 0.04292003, 0.28596526]])

In [9]:
D = np.zeros((2,4))
D

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
A[0][2] # 1행 3열

2

## numpy 행렬 연산

In [15]:
A = np.array([
    [ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2]
       ])

In [16]:
B = np.random.rand(3,3)
B

array([[0.48799877, 0.18812185, 0.9549234 ],
       [0.58124187, 0.12681338, 0.83774583],
       [0.59274641, 0.57167253, 0.29453573]])

In [17]:
A+B

array([[ 1.48799877, -0.81187815,  2.9549234 ],
       [ 3.58124187,  2.12681338,  2.83774583],
       [ 4.59274641,  1.57167253,  2.29453573]])

In [18]:
5*A

array([[ 5, -5, 10],
       [15, 10, 10],
       [20,  5, 10]])

In [19]:
np.dot(A,B)

array([[1.09224971, 1.20465353, 0.70624903],
       [3.81197288, 1.96133737, 5.12933333],
       [3.71872977, 2.02264583, 5.2465109 ]])

In [20]:
A@B

array([[1.09224971, 1.20465353, 0.70624903],
       [3.81197288, 1.96133737, 5.12933333],
       [3.71872977, 2.02264583, 5.2465109 ]])

In [21]:
A*B # 요소 곱

array([[ 0.48799877, -0.18812185,  1.9098468 ],
       [ 1.74372562,  0.25362677,  1.67549166],
       [ 2.37098563,  0.57167253,  0.58907146]])

In [22]:
A@B + (A+2*B)

array([[3.06824726, 0.58089722, 4.61609584],
       [7.97445662, 4.21496413, 8.80482499],
       [8.90422259, 4.1659909 , 7.83558237]])

## 전치, 단위, 역행렬

In [23]:
A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2]])

In [24]:
np.transpose(A) # 전치

array([[ 1,  3,  4],
       [-1,  2,  1],
       [ 2,  2,  2]])

In [25]:
A.T

array([[ 1,  3,  4],
       [-1,  2,  1],
       [ 2,  2,  2]])

In [26]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
A @ np.identity(3)

array([[ 1., -1.,  2.],
       [ 3.,  2.,  2.],
       [ 4.,  1.,  2.]])

In [29]:
A_inv = np.linalg.pinv(A) #pinv 는 역행렬 없어도 비슷한 값 출력해줌
A_inv

array([[-0.2, -0.4,  0.6],
       [-0.2,  0.6, -0.4],
       [ 0.5,  0.5, -0.5]])

In [30]:
A @ A_inv # floating point precision 문제 존재함

array([[ 1.00000000e+00,  7.77156117e-16, -8.88178420e-16],
       [ 0.00000000e+00,  1.00000000e+00, -8.88178420e-16],
       [ 0.00000000e+00,  4.44089210e-16,  1.00000000e+00]])